// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PetPlayBackend.Domain.Contexts;

namespace PetPlayBackend.Domain.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20181021181410_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PetPlayBackend.Domain.Models.Access", b =>
                {
                    b.Property<Guid>("UserId");

                    b.Property<Guid>("ToyId");

                    b.Property<bool>("IsOwner");

                    b.HasKey("UserId", "ToyId");

                    b.HasIndex("ToyId");

                    b.ToTable("Access");
                });

            modelBuilder.Entity("PetPlayBackend.Domain.Models.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Breed");

                    b.Property<string>("Nickname");

                    b.Property<Guid?>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Pets");
                });

            modelBuilder.Entity("PetPlayBackend.Domain.Models.Toy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Model");

                    b.HasKey("Id");

                    b.ToTable("Toys");
                });

            modelBuilder.Entity("PetPlayBackend.Domain.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Nickname");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PetPlayBackend.Domain.Models.Access", b =>
                {
                    b.HasOne("PetPlayBackend.Domain.Models.Toy", "Toy")
                        .WithMany("Accesses")
                        .HasForeignKey("ToyId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PetPlayBackend.Domain.Models.User", "User")
                        .WithMany("Accesses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PetPlayBackend.Domain.Models.Pet", b =>
                {
                    b.HasOne("PetPlayBackend.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
